### PR TITLE
Add a menu navbar

### PR DESCRIPTION
**Pull request by duskotmane**
- [ ] Update HTML code.
- [ ] Update CSSfile and style the menu
- [ ] Create  javascript file
- [ ] Show and hide the menu

### CODE REVIEW

**Comment by nahnahdev** [comment]
## Project Status: INVALIDATED :red_circle: 
Hi @OTMANE-ECHCHAFYKY and @mohametalmeari , 

While you made a great effort in this project, I can't go ahead and review your code.


## Invalid Code Review Request

- This is because you have submitted a project, that is missing the [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) and [HTML&CSS](https://github.com/microverseinc/linters-config/tree/master/html-css) Linters. 
- You should have **5 linter checks** in all including `eslint` linter checks for javascript so kindly include this :wink: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by duskotmane** [comment]
@NahnahAJ How can I set up the javascript linter I forgot to add it, and I don't know to do it.
I would be glad if you can help, please.

**Comment by nahnahdev** [comment]
Sorry for the late response @OTMANE-ECHCHAFYKY , just like you set up the HTML and CSS linters, It's the same way for the [JavaScript](https://github.com/microverseinc/linters-config/tree/master/javascript) Linters. Since you already have HTML and CSS setup, you just need to add the javascript setups to your project. You can follow the guidelines when you open the link to the linter files above :+1: Let me know if you have any questions or concerns

**Comment by duskotmane** [comment]
@NahnahAJ I added the file but the checks are still only 4, without the js check!

**Comment by nahnahdev** [comment]
Did you update the `linters.yml` file with the `eslint` checks? @OTMANE-ECHCHAFYKY

**Review by christianbiring1 — APPROVED** [review]
Hi @OTMANE-ECHCHAFYKY, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
congraaaa

## Highlights
- [ ] All linters checks are set properly :heavy_check_mark: 
- [ ] The hamburger menu is implemented correctly :+1: 
- [ ] Descriptive PR `title` and `summary` :+1: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by duskotmane** [comment]
@christianbiring1 Thank you

**Pull request merged**
